adaltas/node-nikita

- packages/ipa/src/register.coffee
- packages/ipa/src/service/del.coffee.md
- packages/ipa/src/service/exists.coffee.md
- packages/ipa/src/service/show.coffee.md
- packages/ipa/test/service/add.coffee
- packages/ipa/test/service/del.coffee
- packages/ipa/test/service/exists.coffee
- packages/ipa/test/service/show.coffee
Code after review.
Some questions :
- Should I call the "add" function "index" as in /user and /group ?
- I didn't copy schema tests which are in /user/src/index.coffee.
- I left the line 59 of /service/src/del.coffee, which seems useless.
> Ipa service add

- README.md
English grammar polish. New lines after each header to correct formatting
> Readme English polish

- packages/engine/package.json
- packages/engine/src/actions/fs/remove.coffee.md
- packages/engine/src/register.coffee
- packages/engine/test/actions/fs/remove.coffee
Migrate `remove` source action and associated tests.
Remove unused dependencies.
> engine: migrate remove

- packages/engine/src/actions/fs/move.coffee.md
- packages/engine/src/register.coffee
- packages/engine/test/actions/fs/move.coffee
Migrate `system.move` to engine
> engine: migrate move

- packages/engine/src/actions/fs/base/chmod.coffee.md
- packages/engine/test/actions/fs/chmod.coffee
- packages/file/src/index.coffee.md
- packages/file/src/register.coffee
- packages/file/src/touch.coffee.md
- packages/file/src/upload.coffee.md
- packages/file/test/touch.coffee
- packages/file/test/upload.coffee
Migrate `upload` and `touch` from `core` to `engine`.
> File stable

- packages/docker/src/tools/execute.coffee.md
> docker: fix utils

- packages/db/lib/register.js
- packages/db/src/register.coffee
- packages/docker/lib/register.js
- packages/docker/src/register.coffee
- packages/engine/lib/register.js
- packages/engine/src/register.coffee
- packages/file/lib/register.js
- packages/file/src/register.coffee
- packages/ipa/lib/register.js
- packages/ipa/src/register.coffee
- packages/java/lib/register.js
- packages/java/src/register.coffee
- packages/krb5/lib/register.js
- packages/krb5/src/register.coffee
- packages/ldap/lib/register.js
- packages/ldap/src/register.coffee
- packages/lxd/lib/register.js
- packages/lxd/src/register.coffee
- packages/network/lib/register.js
- packages/network/src/register.coffee
- packages/service/lib/register.js
- packages/service/src/register.coffee
- packages/tools/lib/register.js
- packages/tools/src/register.coffee
> fix: catch errors when register actions

- packages/db/lib/user/index.js
- packages/db/src/user/index.coffee.md
> fix(db): move "set password" to "alter user" command

- packages/ipa/env/ipa/start.coffee
- packages/lxd/lib/cluster/index.js
- packages/lxd/lib/cluster/samples/three_nodes.js
- packages/lxd/lib/config/device/delete.js
- packages/lxd/src/cluster/index.coffee.md
- packages/lxd/src/cluster/samples/three_nodes.coffee
- packages/lxd/src/config/device/delete.coffee.md
- packages/lxd/test.sample.coffee
- packages/lxd/test/cluster.coffee
- packages/tools/env/apm/start.coffee
- packages/tools/env/iptables/start.coffee
- packages/tools/env/npm/start.coffee
- packages/tools/env/rubygems.lxd/start.coffee
> fix: schema and lxd environment

- packages/engine/env/centos7/Dockerfile
- packages/engine/env/ubuntu_trusty/Dockerfile
> test(engine): fix ubuntu_trusty environment

- packages/engine/env/arch_chroot/Dockerfile
- packages/engine/env/arch_chroot/test.coffee
- packages/engine/env/centos6/Dockerfile
- packages/engine/env/centos6/docker-compose.yml
- packages/engine/env/centos6/run.sh
- packages/engine/env/centos6/supervisord.conf
- packages/engine/env/centos6/test.coffee
- packages/engine/env/centos7/test.coffee
- packages/engine/env/run.sh
- packages/engine/env/ubuntu_trusty/test.coffee
- packages/engine/lib/plugins/conditions_os.js
- packages/engine/lib/utils/os.js
- packages/engine/src/plugins/conditions_os.coffee
- packages/engine/src/utils/os.coffee
- packages/engine/test/plugins/conditions/if_os.coffee
- packages/engine/test/plugins/conditions/unless_os.coffee
> fix(engine): os conditions for archlinux

- packages/service/env/centos6/Dockerfile
- packages/service/env/centos6/test.coffee
- packages/service/env/run.sh
> test(service): fix centos 6 environment

- packages/service/lib/startup.js
- packages/service/src/startup.coffee.md
It fixes the `chkconfig` command used in `@service.startup`
> fix(service): startup with chkconfig

- docs/content/about/tutorial.md
- docs/content/about/tutorial/samples/call.converted.js
- docs/content/about/tutorial/samples/call.js
- docs/content/about/tutorial/samples/config/app.js
- docs/content/about/tutorial/samples/config/lib/touch.js
- docs/content/about/tutorial/samples/config/register.js
- docs/content/about/tutorial/samples/external/app.js
- docs/content/about/tutorial/samples/external/lib/touch.js
- docs/content/about/tutorial/samples/idempotence.js
- docs/content/about/tutorial/samples/promise.js
- docs/content/about/tutorial/samples/promise_parent.js
- docs/content/about/tutorial/samples/promise_sequence.js
- docs/content/about/tutorial/samples/redis/1.compile.js
- docs/content/about/tutorial/samples/redis/1.compile_cwd.js
- docs/content/about/tutorial/samples/redis/1.download.js
- docs/content/about/tutorial/samples/redis/2.config.js
- docs/content/about/tutorial/samples/redis/3.log_cli.js
- docs/content/about/tutorial/samples/redis/3.log_md.js
- docs/content/about/tutorial/samples/redis/4.start.js
- docs/content/about/tutorial/samples/redis/5.health.js
- docs/content/about/tutorial/samples/redis/5.health_arrow.js
- docs/content/about/tutorial/samples/redis/6.ssh.js
- docs/content/about/tutorial/samples/redis/7.composition/app.js
- docs/content/about/tutorial/samples/redis/7.composition/index.js
- docs/content/about/tutorial/samples/redis/7.composition/lib/check.js
- docs/content/about/tutorial/samples/redis/7.composition/lib/install.js
It is not meant to be merged as is. It requires a few updates such as for "Scheduling actions" section and improving consistency and correcting the samples.
Leave your comments if you have some.
> docs: update tutorial

- docs/content/usages/conditions/index.md
- docs/content/usages/conditions/samples/example.js
An update to make consistent to assertions page
> docs: update usages/conditions page

- docs/content/usages/registry.md
I didn't change this page a lot. Specify if something is missing.
> docs: update usages/registry page

- packages/core/test/actions/fs/remove.coffee
> fix(core): fix folder removal error message

- packages/tools/lib/repo.js
- packages/tools/src/repo.coffee.md
- packages/tools/test/repo.coffee
> feat(tools): add option to download gpg key to repo tool

- packages/lxd/src/query.coffee.md
- packages/lxd/test/query.coffee
Adding more options for `lxc.query` to allow for creation, deletion and modifications of containers, storage, etc...
It will be need for the implementation of other pull requests.
> feat(lxd): lxc query more options

- packages/lxd/src/config/device/index.coffee.md
Fix issue https://github.com/adaltas/node-nikita/issues/387
> feat(lxd): lxc.config.device disk source not required

- packages/lxd/test/file/exists.coffee
> fix(lxd): unwanted $ sign in lxc.file.exists

- packages/lxd/package.json
- packages/lxd/src/file/pull.coffee.md
- packages/lxd/src/register.coffee
- packages/lxd/test/file/pull.coffee
Feature allowing a user to pull a file from an instance.
```coffeescript
await @lxc.file.pull 
$header: "[action]"
container: '[your container]'
source: '[path to the file in the container]'
target: '[path to the local folder]'
```
> feat(lxd): lxd.file.pull package

- packages/lxd/src/state.coffee.md
Usage of `lxc.query` for `lxc.state`.
> refactor(lxd): lxc.state using lxc.query

- packages/lxd/test/file/push.coffee
Using `lxd 5.0.0`, the following test do not pass anymore:
```coffeescript
describe 'usage', ->
they "a new file"
```
I reworked the test to include `lxc.cluster`, to be sure that the network is properly created. Also using await where it wasn't the case.
> fix(lxd): lxc.file.push test fix

- docs/website/src/pages/index.js
Fixing some inconsistencies between readme.md and index.js, as well as correcting some typos.
> docs(website): corrected typos on index.js

- packages/lxd/test/file/pull.coffee
Removed abusive usage of `lxc.cluster` for testing.
> fix(lxd): lxc.file.pull test fix

- README.md
> fix: README.md typos
